version: '3.1'
services:
  stark_db:
    image: postgres:10.5-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sa
      POSTGRES_DB: stark_db
    volumes:
      - vl-stark_db:/var/lib/postgresql/data
    ports:
     - "5433:5432"
  staging-stark2-api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
     - ./:/opt/app
    working_dir: /opt/app
    env_file: ./.env
    ports:
     - "3000:3000"
     - "9000:9000"
    depends_on:
      - stark_db
    command: ash -c "npm run build && npm start"

volumes:
  vl-stark_db:
    driver_opts:
      type: tmpfs
      device: tmpfs
#   driver: local
